# coding: utf-8

"""
    VisWiz.io API Documentation

    This SDK allows you to query and create new projects, builds or images within the VisWiz service.   # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: support@viswiz.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viswiz_sdk
from Client.builds_api import BuildsApi  # noqa: E501
from viswiz_sdk.rest import ApiException


class TestBuildsApi(unittest.TestCase):
    """BuildsApi unit test stubs"""

    def setUp(self):
        self.api = Client.builds_api.BuildsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_build(self):
        """Test case for create_build

        Create a build  # noqa: E501
        """
        pass

    def test_finish_build(self):
        """Test case for finish_build

        Finish a build  # noqa: E501
        """
        pass

    def test_get_build_results(self):
        """Test case for get_build_results

        Get results for a build  # noqa: E501
        """
        pass

    def test_get_builds(self):
        """Test case for get_builds

        Get builds for a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
