# coding: utf-8

"""
    VisWiz.io API Documentation

    This SDK allows you to query and create new projects, builds or images within the VisWiz service.   # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: support@viswiz.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viswiz_sdk
from Client.plans_api import PlansApi  # noqa: E501
from viswiz_sdk.rest import ApiException


class TestPlansApi(unittest.TestCase):
    """PlansApi unit test stubs"""

    def setUp(self):
        self.api = Client.plans_api.PlansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_plan(self):
        """Test case for cancel_plan

        Cancel the active plan  # noqa: E501
        """
        pass

    def test_get_plans(self):
        """Test case for get_plans

        Get all plans  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
