# coding: utf-8

"""
    VisWiz.io API Documentation

    This SDK allows you to query and create new projects, builds or images within the VisWiz service.   # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: support@viswiz.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viswiz_sdk
from Client.images_api import ImagesApi  # noqa: E501
from viswiz_sdk.rest import ApiException


class TestImagesApi(unittest.TestCase):
    """ImagesApi unit test stubs"""

    def setUp(self):
        self.api = Client.images_api.ImagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_image(self):
        """Test case for create_image

        Create an image  # noqa: E501
        """
        pass

    def test_get_images(self):
        """Test case for get_images

        Get images for a build  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
