# coding: utf-8

"""
    VisWiz.io API Documentation

    This SDK allows you to query and create new projects, builds or images within the VisWiz service.   # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: support@viswiz.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viswiz_sdk
from viswiz_sdk.models.account_api_keys import AccountApiKeys  # noqa: E501
from viswiz_sdk.rest import ApiException


class TestAccountApiKeys(unittest.TestCase):
    """AccountApiKeys unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountApiKeys(self):
        """Test AccountApiKeys"""
        # FIXME: construct object with mandatory attributes with example values
        # model = viswiz_sdk.models.account_api_keys.AccountApiKeys()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
